### PR TITLE
fix: project doesn't build due to kotlin gradle plugin incompatibility

### LINKED ISSUE #30: fix: project doesn't build due to kotlin gradle plugin incompatibility
**Description**
Project doesn't build

**Steps To Reproduce**

1. Check out plain project
2. Resolve dependencies, try to run
3. Observe build error

```
Launching lib/main_development.dart on sdk gwear arm64 in debug mode...
Running Gradle task 'assembleDevelopmentDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':wear' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Expected Behavior**

**Screenshots**

**Additional Context**
There has been an issue filed with wear but it doesn't seem to get any traction. 
https://github.com/fluttercommunity/flutter_wear_plugin/issues/25

### PR DESCRIPTION
**Pull request by renancaraujo**
## Description

fix #30 

This internalizes the implementation of ambient mode handling. 

Unlike the plugin, it uses the updated `AmbientModeSupport` API. 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: src/my_app/lib/app/view/app.dart [hunk 1]
```diff
@@ -1,17 +1,16 @@
...
   const App({super.key});
 
   @override
   Widget build(BuildContext context) {
-    // Add ambient mode support
-    return AmbientMode(
+    return AmbientModeBuilder(
       child: const CounterPage(),
-      builder: (context, mode, child) {
+      builder: (context, ambientModeActive, child) {
```
Comment (alestiago) [inline src/my_app/lib/app/view/app.dart:13]: **Nit:**

```suggestion
      builder: (context, isAmbientModeActive, child) {
```

File: src/my_app/test/ambient_mode/view/ambient_mode_builder_test.dart [hunk 2]
```diff
@@ -0,0 +1,45 @@
+import 'package:flutter/material.dart';
+import 'package:flutter_test/flutter_test.dart';
+import 'package:very_good_wearos_app/ambient_mode/ambient_mode.dart';
+
+class TestAmbientModeListener extends ValueNotifier<bool>
```
Comment (alestiago) [inline src/my_app/test/ambient_mode/view/ambient_mode_builder_test.dart:5]: **Nit:**

```suggestion
class _TestAmbientModeListener extends ValueNotifier<bool>
```

**Review by alestiago — APPROVED** [review]

File: src/my_app/pubspec.yaml [hunk 3]
```diff
@@ -14,7 +14,6 @@ dependencies:
   flutter_localizations:
     sdk: flutter
   intl: ^0.18.0
-  wear: ^1.1.0
```
Comment (alestiago) [inline src/my_app/pubspec.yaml:17]: 👋 [goodbye](https://www.youtube.com/watch?v=wVyggTKDcOE)

**Review by alestiago — APPROVED** [review]

**Review by alestiago — APPROVED** [review]
